// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjCAuRalYtSbvUHbMBvnBl_50G7e5xkPM',
    appId: '1:936257818760:web:6724e887ac6b5de24b4f3d',
    messagingSenderId: '936257818760',
    projectId: 'flavor-bistro',
    authDomain: 'flavor-bistro.firebaseapp.com',
    storageBucket: 'flavor-bistro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNX37jl_DE_dXMFBUm-MoYosQLISfH0cM',
    appId: '1:936257818760:android:4fd1a17608f0998e4b4f3d',
    messagingSenderId: '936257818760',
    projectId: 'flavor-bistro',
    storageBucket: 'flavor-bistro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_oqP1pE4Byiez9MoUM1w2mq3PDbxpjlg',
    appId: '1:936257818760:ios:cf5e73cf3ebdfbd24b4f3d',
    messagingSenderId: '936257818760',
    projectId: 'flavor-bistro',
    storageBucket: 'flavor-bistro.appspot.com',
    iosBundleId: 'com.example.flavorBistro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_oqP1pE4Byiez9MoUM1w2mq3PDbxpjlg',
    appId: '1:936257818760:ios:992e0b9f9e1ebe364b4f3d',
    messagingSenderId: '936257818760',
    projectId: 'flavor-bistro',
    storageBucket: 'flavor-bistro.appspot.com',
    iosBundleId: 'com.example.flavorBistro.RunnerTests',
  );
}
